services:
  base:
    image: registry.k8s.io/pause:3.10
    ports:
      - "8080:8080"
  plugin:
    build:
      context: .
      target: develop
    network_mode: "service:base"
    environment:
      NODE_NAME: builder-03a
      KUBECONFIG: /etc/kubernetes/kubeconfig
    command:
      - "make"
      - "run"
    volumes:
      - type: volume
        source: socket-dir
        target: /csi
      - type: bind
        source: ./hack
        target: /etc/kubernetes
      - type: bind
        source: ./
        target: /src
  csi-attacher:
    image: registry.k8s.io/sig-storage/csi-attacher:v4.8.1
    network_mode: "service:base"
    command:
      - "--v=5"
      - "--csi-address=unix:///csi/csi.sock"
      - "--leader-election=false"
      - "--default-fstype=ext4"
      - "--kubeconfig=/etc/kubernetes/kubeconfig"
    volumes:
      - type: volume
        source: socket-dir
        target: /csi
      - type: bind
        source: ./hack
        target: /etc/kubernetes
  csi-provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
    network_mode: "service:base"
    command:
      - "--v=5"
      - "--timeout=360s"
      - "--csi-address=unix:///csi/csi.sock"
      - "--leader-election=false"
      - "--default-fstype=ext4"
      - "--feature-gates=Topology=true"
      # - "--enable-capacity"
      # - "--capacity-ownerref-level=-1"
      # - "--capacity-poll-interval=2m"
      - "--extra-create-metadata=true"
      # - "--node-deployment"
      - "--kubeconfig=/etc/kubernetes/kubeconfig"
    environment:
      NAMESPACE: csi-hybrid
      POD_NAME: csi-provisioner
      NODE_NAME: builder-03a
    volumes:
      - type: volume
        source: socket-dir
        target: /csi
      - type: bind
        source: ./hack
        target: /etc/kubernetes
  # csi-node-driver-registrar:
  #   image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.12.0
  #   network_mode: "service:base"
  #   command:
  #     - "--v=5"
  #     - "--csi-address=unix:///csi/csi.sock"
  #     - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.hybrid.sinextra.dev/csi.sock"
  #   environment:
  #     KUBE_NODE_NAME: builder-03a
  #   volumes:
  #     - type: volume
  #       source: socket-dir
  #       target: /csi
  #     - type: bind
  #       source: ./hack
  #       target: /etc/kubernetes

volumes:
  socket-dir:
