# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: hybrid-csi-plugin
description: Container Storage Interface plugin
type: application
home: https://github.com/sergelogvinov/hybrid-csi-plugin
icon: https://raw.githubusercontent.com/sergelogvinov/hybrid-csi-plugin/main/charts/hybrid-csi-plugin/icon.png
sources:
  - https://github.com/sergelogvinov/hybrid-csi-plugin
keywords:
  - csi
  - storage
  - block-storage
  - volume
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov
#
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.3
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: v0.1.0
