createNamespace: true

image:
  pullPolicy: Always
  tag: edge

storageClass: []
#   - name: hybrid
#     storageClasses: proxmox

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
