{{- range $storage := .Values.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storage.name | required "StorageClass name must be provided." }}
  {{- with $storage.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- if $storage.default }}
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  {{- with $storage.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: {{ $.Values.provisionerName }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ default "Delete" $storage.reclaimPolicy }}
parameters:
  storageClasses: {{ $storage.storageClasses | required "Storage classes must be provided." }}
{{- with $storage.allowedTopologies }}
allowedTopologies:
  {{- . | toYaml | nindent 2 }}
{{- end }}
---
{{- end }}
